# Проверка lagkit на синтетических данных

Витрина: 01.07.2026 – 01.09.2026, три фактора с разной частотностью; у каждого в master задан лаг.

| factor | частотность | лаг | как лежит в витрине |
|---|---|---|---|
| `usd_rub` | д | 1 | значение каждый день; 01.09 ещё не загружено (хвост) |
| `cpi_mom` | м | 30 | плотная раскладка: 01.07–31.07 = 100.0, 01.08–01.09 = 101.5 (сентябрьского отчёта ещё нет) |
| `deposits_w` | н | 3 | плотная раскладка, отчёт по понедельникам (первый — 01.07, среда); неделя 10.08 **не загружена** (сбой); отчёт 31.08 ещё не пришёл |

Ожидания:
* `usd_rub`: на дату t стоит значение витрины за t−1.
* `cpi_mom`: 100.0 известно с 31.07 (01.07+30), 101.5 — с 31.08 (01.08+30); до 31.07 пусто.
* `deposits_w`: отчёт за понедельник d известен с d+3 (четверг); во время сбоя протягивается значение отчёта 03.08, пока 20.08 не станет известен отчёт 17.08.

In [1]:
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path.cwd()))  # папка lagkit лежит рядом с ноутбуком
from lagkit import LagProcessor

pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 160)
OUT = Path("synthetic")
OUT.mkdir(exist_ok=True)

## 1. Синтетические master и data

In [2]:
master = pd.DataFrame({
    "factor":         ["usd_rub", "cpi_mom", "deposits_w"],
    "data_frequency": ["д",       "м",       "н"],
    "object_lag":     [1,          30,        3],
})

dates = pd.date_range("2026-07-01", "2026-09-01", freq="D")
data = pd.DataFrame({"DATE": dates})

# Дневной курс: своё значение каждый день, 01.09 ещё не загружено.
data["usd_rub"] = np.round(90 + 0.1 * np.arange(len(dates)), 2)
data.loc[data["DATE"] == "2026-09-01", "usd_rub"] = np.nan

# Месячный индекс в плотной раскладке.
data["cpi_mom"] = np.where(data["DATE"] < "2026-08-01", 100.0, 101.5)

# Недельный ряд: новое значение каждый понедельник (+ первый отчёт 01.07), ffill внутри недели.
week_start = data["DATE"].dt.to_period("W-SUN").dt.start_time.clip(lower=dates[0])
week_no = week_start.rank(method="dense").astype(int) - 1
data["deposits_w"] = 7.0 + 0.25 * week_no
data.loc[data["DATE"].between("2026-08-10", "2026-08-16"), "deposits_w"] = np.nan  # сбой загрузки
# Отчёт за 31.08 ещё не загружен: витрина протянула значение отчёта 24.08 до конца.
data.loc[data["DATE"] >= "2026-08-31", "deposits_w"] = 9.0

master.to_csv(OUT / "master.csv", index=False, sep=";", encoding="utf-8")
# Витрина в «российском» виде: ДД.ММ.ГГГГ, разделитель ';', десятичная запятая.
data_csv = data.copy()
data_csv["DATE"] = data_csv["DATE"].dt.strftime("%d.%m.%Y")
data_csv.to_csv(OUT / "data.csv", index=False, sep=";", decimal=",", encoding="utf-8")

print((OUT / "master.csv").read_text())
print("\n".join((OUT / "data.csv").read_text().splitlines()[:8]), "\n...")

factor;data_frequency;object_lag
usd_rub;д;1
cpi_mom;м;30
deposits_w;н;3

DATE;usd_rub;cpi_mom;deposits_w
01.07.2026;90,0;100,0;7,0
02.07.2026;90,1;100,0;7,0
03.07.2026;90,2;100,0;7,0
04.07.2026;90,3;100,0;7,0
05.07.2026;90,4;100,0;7,0
06.07.2026;90,5;100,0;7,25
07.07.2026;90,6;100,0;7,25
...

## 2. Обработка lagkit

In [3]:
lp = LagProcessor(master=OUT / "master.csv", data=OUT / "data.csv",
                  config={"output_format": "csv", "output_dir": str(OUT / "lag_output")})
lp.lags

       factor data_frequency  object_lag lag_source layout
0     usd_rub              д           1     master  daily
1     cpi_mom              м          30     master  dense
2  deposits_w              н           3     master  dense

In [4]:
lp.publications  # одна строка на отчёт: report_date -> available_date

        factor report_date  block_end available_date   value
0      usd_rub  2026-07-01 2026-07-01     2026-07-02   90.00
1      usd_rub  2026-07-02 2026-07-02     2026-07-03   90.10
2      usd_rub  2026-07-03 2026-07-03     2026-07-04   90.20
3      usd_rub  2026-07-04 2026-07-04     2026-07-05   90.30
4      usd_rub  2026-07-05 2026-07-05     2026-07-06   90.40
5      usd_rub  2026-07-06 2026-07-06     2026-07-07   90.50
6      usd_rub  2026-07-07 2026-07-07     2026-07-08   90.60
7      usd_rub  2026-07-08 2026-07-08     2026-07-09   90.70
8      usd_rub  2026-07-09 2026-07-09     2026-07-10   90.80
9      usd_rub  2026-07-10 2026-07-10     2026-07-11   90.90
10     usd_rub  2026-07-11 2026-07-11     2026-07-12   91.00
11     usd_rub  2026-07-12 2026-07-12     2026-07-13   91.10
12     usd_rub  2026-07-13 2026-07-13     2026-07-14   91.20
13     usd_rub  2026-07-14 2026-07-14     2026-07-15   91.30
14     usd_rub  2026-07-15 2026-07-15     2026-07-16   91.40
15     usd_rub  2026-07-16 2026-07-16     2026-07-17   91.50
16     usd_rub  2026-07-17 2026-07-17     2026-07-18   91.60
17     usd_rub  2026-07-18 2026-07-18     2026-07-19   91.70
18     usd_rub  2026-07-19 2026-07-19     2026-07-20   91.80
19     usd_rub  2026-07-20 2026-07-20     2026-07-21   91.90
20     usd_rub  2026-07-21 2026-07-21     2026-07-22   92.00
21     usd_rub  2026-07-22 2026-07-22     2026-07-23   92.10
22     usd_rub  2026-07-23 2026-07-23     2026-07-24   92.20
23     usd_rub  2026-07-24 2026-07-24     2026-07-25   92.30
24     usd_rub  2026-07-25 2026-07-25     2026-07-26   92.40
25     usd_rub  2026-07-26 2026-07-26     2026-07-27   92.50
26     usd_rub  2026-07-27 2026-07-27     2026-07-28   92.60
27     usd_rub  2026-07-28 2026-07-28     2026-07-29   92.70
28     usd_rub  2026-07-29 2026-07-29     2026-07-30   92.80
29     usd_rub  2026-07-30 2026-07-30     2026-07-31   92.90
30     usd_rub  2026-07-31 2026-07-31     2026-08-01   93.00
31     usd_rub  2026-08-01 2026-08-01     2026-08-02   93.10
32     usd_rub  2026-08-02 2026-08-02     2026-08-03   93.20
33     usd_rub  2026-08-03 2026-08-03     2026-08-04   93.30
34     usd_rub  2026-08-04 2026-08-04     2026-08-05   93.40
35     usd_rub  2026-08-05 2026-08-05     2026-08-06   93.50
36     usd_rub  2026-08-06 2026-08-06     2026-08-07   93.60
37     usd_rub  2026-08-07 2026-08-07     2026-08-08   93.70
38     usd_rub  2026-08-08 2026-08-08     2026-08-09   93.80
39     usd_rub  2026-08-09 2026-08-09     2026-08-10   93.90
40     usd_rub  2026-08-10 2026-08-10     2026-08-11   94.00
41     usd_rub  2026-08-11 2026-08-11     2026-08-12   94.10
42     usd_rub  2026-08-12 2026-08-12     2026-08-13   94.20
43     usd_rub  2026-08-13 2026-08-13     2026-08-14   94.30
44     usd_rub  2026-08-14 2026-08-14     2026-08-15   94.40
45     usd_rub  2026-08-15 2026-08-15     2026-08-16   94.50
46     usd_rub  2026-08-16 2026-08-16     2026-08-17   94.60
47     usd_rub  2026-08-17 2026-08-17     2026-08-18   94.70
48     usd_rub  2026-08-18 2026-08-18     2026-08-19   94.80
49     usd_rub  2026-08-19 2026-08-19     2026-08-20   94.90
50     usd_rub  2026-08-20 2026-08-20     2026-08-21   95.00
51     usd_rub  2026-08-21 2026-08-21     2026-08-22   95.10
52     usd_rub  2026-08-22 2026-08-22     2026-08-23   95.20
53     usd_rub  2026-08-23 2026-08-23     2026-08-24   95.30
54     usd_rub  2026-08-24 2026-08-24     2026-08-25   95.40
55     usd_rub  2026-08-25 2026-08-25     2026-08-26   95.50
56     usd_rub  2026-08-26 2026-08-26     2026-08-27   95.60
57     usd_rub  2026-08-27 2026-08-27     2026-08-28   95.70
58     usd_rub  2026-08-28 2026-08-28     2026-08-29   95.80
59     usd_rub  2026-08-29 2026-08-29     2026-08-30   95.90
60     usd_rub  2026-08-30 2026-08-30     2026-08-31   96.00
61     usd_rub  2026-08-31 2026-08-31     2026-09-01   96.10
62     cpi_mom  2026-07-01 2026-07-31     2026-07-31  100.00
63     cpi_mom  2026-08-01 2026-09-01     2026-08-31  101.50
64  deposits_w  2026-07-01 2026-07-05     2026-07-04    7.00
65  deposits_w  2026-07-06 2026-07-12     2026-07-09    7.25
66  deposits_w  2026-07-13 2026-07-19     2026-07-16    7.50
67  deposits_w  2026-07-20 2026-07-26     2026-07-23    7.75
68  deposits_w  2026-07-27 2026-08-02     2026-07-30    8.00
69  deposits_w  2026-08-03 2026-08-09     2026-08-06    8.25
70  deposits_w  2026-08-17 2026-08-23     2026-08-20    8.75
71  deposits_w  2026-08-24 2026-09-01     2026-08-27    9.00

In [5]:
lp.diagnostics()

       factor            check severity                                            message                                            details
0  deposits_w  missing_reports  warning  Пропуски отчётов: 1 разрыв(ов), всего пропущен...  [{"prev_report": "03.08.2026", "next_report": ...

## 3. Трассировка каждого фактора: raw → журнал → known

In [6]:
for f in lp.factors:
    print(f"=== {f} ===")
    display(lp.trace(f))

=== usd_rub ===

         DATE   raw  journal available_date  is_filled  known
0  2026-07-01  90.0     90.0     2026-07-02      False    NaN
1  2026-07-02  90.1     90.1     2026-07-03      False   90.0
2  2026-07-03  90.2     90.2     2026-07-04      False   90.1
3  2026-07-04  90.3     90.3     2026-07-05      False   90.2
4  2026-07-05  90.4     90.4     2026-07-06      False   90.3
5  2026-07-06  90.5     90.5     2026-07-07      False   90.4
6  2026-07-07  90.6     90.6     2026-07-08      False   90.5
7  2026-07-08  90.7     90.7     2026-07-09      False   90.6
8  2026-07-09  90.8     90.8     2026-07-10      False   90.7
9  2026-07-10  90.9     90.9     2026-07-11      False   90.8
10 2026-07-11  91.0     91.0     2026-07-12      False   90.9
11 2026-07-12  91.1     91.1     2026-07-13      False   91.0
12 2026-07-13  91.2     91.2     2026-07-14      False   91.1
13 2026-07-14  91.3     91.3     2026-07-15      False   91.2
14 2026-07-15  91.4     91.4     2026-07-16      False   91.3
15 2026-07-16  91.5     91.5     2026-07-17      False   91.4
16 2026-07-17  91.6     91.6     2026-07-18      False   91.5
17 2026-07-18  91.7     91.7     2026-07-19      False   91.6
18 2026-07-19  91.8     91.8     2026-07-20      False   91.7
19 2026-07-20  91.9     91.9     2026-07-21      False   91.8
20 2026-07-21  92.0     92.0     2026-07-22      False   91.9
21 2026-07-22  92.1     92.1     2026-07-23      False   92.0
22 2026-07-23  92.2     92.2     2026-07-24      False   92.1
23 2026-07-24  92.3     92.3     2026-07-25      False   92.2
24 2026-07-25  92.4     92.4     2026-07-26      False   92.3
25 2026-07-26  92.5     92.5     2026-07-27      False   92.4
26 2026-07-27  92.6     92.6     2026-07-28      False   92.5
27 2026-07-28  92.7     92.7     2026-07-29      False   92.6
28 2026-07-29  92.8     92.8     2026-07-30      False   92.7
29 2026-07-30  92.9     92.9     2026-07-31      False   92.8
30 2026-07-31  93.0     93.0     2026-08-01      False   92.9
31 2026-08-01  93.1     93.1     2026-08-02      False   93.0
32 2026-08-02  93.2     93.2     2026-08-03      False   93.1
33 2026-08-03  93.3     93.3     2026-08-04      False   93.2
34 2026-08-04  93.4     93.4     2026-08-05      False   93.3
35 2026-08-05  93.5     93.5     2026-08-06      False   93.4
36 2026-08-06  93.6     93.6     2026-08-07      False   93.5
37 2026-08-07  93.7     93.7     2026-08-08      False   93.6
38 2026-08-08  93.8     93.8     2026-08-09      False   93.7
39 2026-08-09  93.9     93.9     2026-08-10      False   93.8
40 2026-08-10  94.0     94.0     2026-08-11      False   93.9
41 2026-08-11  94.1     94.1     2026-08-12      False   94.0
42 2026-08-12  94.2     94.2     2026-08-13      False   94.1
43 2026-08-13  94.3     94.3     2026-08-14      False   94.2
44 2026-08-14  94.4     94.4     2026-08-15      False   94.3
45 2026-08-15  94.5     94.5     2026-08-16      False   94.4
46 2026-08-16  94.6     94.6     2026-08-17      False   94.5
47 2026-08-17  94.7     94.7     2026-08-18      False   94.6
48 2026-08-18  94.8     94.8     2026-08-19      False   94.7
49 2026-08-19  94.9     94.9     2026-08-20      False   94.8
50 2026-08-20  95.0     95.0     2026-08-21      False   94.9
51 2026-08-21  95.1     95.1     2026-08-22      False   95.0
52 2026-08-22  95.2     95.2     2026-08-23      False   95.1
53 2026-08-23  95.3     95.3     2026-08-24      False   95.2
54 2026-08-24  95.4     95.4     2026-08-25      False   95.3
55 2026-08-25  95.5     95.5     2026-08-26      False   95.4
56 2026-08-26  95.6     95.6     2026-08-27      False   95.5
57 2026-08-27  95.7     95.7     2026-08-28      False   95.6
58 2026-08-28  95.8     95.8     2026-08-29      False   95.7
59 2026-08-29  95.9     95.9     2026-08-30      False   95.8
60 2026-08-30  96.0     96.0     2026-08-31      False   95.9
61 2026-08-31  96.1     96.1     2026-09-01      False   96.0
62 2026-09-01   NaN     96.1     2026-09-01       True   96.1

=== cpi_mom ===

         DATE    raw  journal available_date  is_filled  known
0  2026-07-01  100.0    100.0     2026-07-31      False    NaN
1  2026-07-02  100.0    100.0     2026-07-31      False    NaN
2  2026-07-03  100.0    100.0     2026-07-31      False    NaN
3  2026-07-04  100.0    100.0     2026-07-31      False    NaN
4  2026-07-05  100.0    100.0     2026-07-31      False    NaN
5  2026-07-06  100.0    100.0     2026-07-31      False    NaN
6  2026-07-07  100.0    100.0     2026-07-31      False    NaN
7  2026-07-08  100.0    100.0     2026-07-31      False    NaN
8  2026-07-09  100.0    100.0     2026-07-31      False    NaN
9  2026-07-10  100.0    100.0     2026-07-31      False    NaN
10 2026-07-11  100.0    100.0     2026-07-31      False    NaN
11 2026-07-12  100.0    100.0     2026-07-31      False    NaN
12 2026-07-13  100.0    100.0     2026-07-31      False    NaN
13 2026-07-14  100.0    100.0     2026-07-31      False    NaN
14 2026-07-15  100.0    100.0     2026-07-31      False    NaN
15 2026-07-16  100.0    100.0     2026-07-31      False    NaN
16 2026-07-17  100.0    100.0     2026-07-31      False    NaN
17 2026-07-18  100.0    100.0     2026-07-31      False    NaN
18 2026-07-19  100.0    100.0     2026-07-31      False    NaN
19 2026-07-20  100.0    100.0     2026-07-31      False    NaN
20 2026-07-21  100.0    100.0     2026-07-31      False    NaN
21 2026-07-22  100.0    100.0     2026-07-31      False    NaN
22 2026-07-23  100.0    100.0     2026-07-31      False    NaN
23 2026-07-24  100.0    100.0     2026-07-31      False    NaN
24 2026-07-25  100.0    100.0     2026-07-31      False    NaN
25 2026-07-26  100.0    100.0     2026-07-31      False    NaN
26 2026-07-27  100.0    100.0     2026-07-31      False    NaN
27 2026-07-28  100.0    100.0     2026-07-31      False    NaN
28 2026-07-29  100.0    100.0     2026-07-31      False    NaN
29 2026-07-30  100.0    100.0     2026-07-31      False    NaN
30 2026-07-31  100.0    100.0     2026-07-31      False  100.0
31 2026-08-01  101.5    101.5     2026-08-31      False  100.0
32 2026-08-02  101.5    101.5     2026-08-31      False  100.0
33 2026-08-03  101.5    101.5     2026-08-31      False  100.0
34 2026-08-04  101.5    101.5     2026-08-31      False  100.0
35 2026-08-05  101.5    101.5     2026-08-31      False  100.0
36 2026-08-06  101.5    101.5     2026-08-31      False  100.0
37 2026-08-07  101.5    101.5     2026-08-31      False  100.0
38 2026-08-08  101.5    101.5     2026-08-31      False  100.0
39 2026-08-09  101.5    101.5     2026-08-31      False  100.0
40 2026-08-10  101.5    101.5     2026-08-31      False  100.0
41 2026-08-11  101.5    101.5     2026-08-31      False  100.0
42 2026-08-12  101.5    101.5     2026-08-31      False  100.0
43 2026-08-13  101.5    101.5     2026-08-31      False  100.0
44 2026-08-14  101.5    101.5     2026-08-31      False  100.0
45 2026-08-15  101.5    101.5     2026-08-31      False  100.0
46 2026-08-16  101.5    101.5     2026-08-31      False  100.0
47 2026-08-17  101.5    101.5     2026-08-31      False  100.0
48 2026-08-18  101.5    101.5     2026-08-31      False  100.0
49 2026-08-19  101.5    101.5     2026-08-31      False  100.0
50 2026-08-20  101.5    101.5     2026-08-31      False  100.0
51 2026-08-21  101.5    101.5     2026-08-31      False  100.0
52 2026-08-22  101.5    101.5     2026-08-31      False  100.0
53 2026-08-23  101.5    101.5     2026-08-31      False  100.0
54 2026-08-24  101.5    101.5     2026-08-31      False  100.0
55 2026-08-25  101.5    101.5     2026-08-31      False  100.0
56 2026-08-26  101.5    101.5     2026-08-31      False  100.0
57 2026-08-27  101.5    101.5     2026-08-31      False  100.0
58 2026-08-28  101.5    101.5     2026-08-31      False  100.0
59 2026-08-29  101.5    101.5     2026-08-31      False  100.0
60 2026-08-30  101.5    101.5     2026-08-31      False  100.0
61 2026-08-31  101.5    101.5     2026-08-31      False  101.5
62 2026-09-01  101.5    101.5     2026-08-31      False  101.5

=== deposits_w ===

         DATE   raw  journal available_date  is_filled  known
0  2026-07-01  7.00     7.00     2026-07-04      False    NaN
1  2026-07-02  7.00     7.00     2026-07-04      False    NaN
2  2026-07-03  7.00     7.00     2026-07-04      False    NaN
3  2026-07-04  7.00     7.00     2026-07-04      False   7.00
4  2026-07-05  7.00     7.00     2026-07-04      False   7.00
5  2026-07-06  7.25     7.25     2026-07-09      False   7.00
6  2026-07-07  7.25     7.25     2026-07-09      False   7.00
7  2026-07-08  7.25     7.25     2026-07-09      False   7.00
8  2026-07-09  7.25     7.25     2026-07-09      False   7.25
9  2026-07-10  7.25     7.25     2026-07-09      False   7.25
10 2026-07-11  7.25     7.25     2026-07-09      False   7.25
11 2026-07-12  7.25     7.25     2026-07-09      False   7.25
12 2026-07-13  7.50     7.50     2026-07-16      False   7.25
13 2026-07-14  7.50     7.50     2026-07-16      False   7.25
14 2026-07-15  7.50     7.50     2026-07-16      False   7.25
15 2026-07-16  7.50     7.50     2026-07-16      False   7.50
16 2026-07-17  7.50     7.50     2026-07-16      False   7.50
17 2026-07-18  7.50     7.50     2026-07-16      False   7.50
18 2026-07-19  7.50     7.50     2026-07-16      False   7.50
19 2026-07-20  7.75     7.75     2026-07-23      False   7.50
20 2026-07-21  7.75     7.75     2026-07-23      False   7.50
21 2026-07-22  7.75     7.75     2026-07-23      False   7.50
22 2026-07-23  7.75     7.75     2026-07-23      False   7.75
23 2026-07-24  7.75     7.75     2026-07-23      False   7.75
24 2026-07-25  7.75     7.75     2026-07-23      False   7.75
25 2026-07-26  7.75     7.75     2026-07-23      False   7.75
26 2026-07-27  8.00     8.00     2026-07-30      False   7.75
27 2026-07-28  8.00     8.00     2026-07-30      False   7.75
28 2026-07-29  8.00     8.00     2026-07-30      False   7.75
29 2026-07-30  8.00     8.00     2026-07-30      False   8.00
30 2026-07-31  8.00     8.00     2026-07-30      False   8.00
31 2026-08-01  8.00     8.00     2026-07-30      False   8.00
32 2026-08-02  8.00     8.00     2026-07-30      False   8.00
33 2026-08-03  8.25     8.25     2026-08-06      False   8.00
34 2026-08-04  8.25     8.25     2026-08-06      False   8.00
35 2026-08-05  8.25     8.25     2026-08-06      False   8.00
36 2026-08-06  8.25     8.25     2026-08-06      False   8.25
37 2026-08-07  8.25     8.25     2026-08-06      False   8.25
38 2026-08-08  8.25     8.25     2026-08-06      False   8.25
39 2026-08-09  8.25     8.25     2026-08-06      False   8.25
40 2026-08-10   NaN     8.25     2026-08-06       True   8.25
41 2026-08-11   NaN     8.25     2026-08-06       True   8.25
42 2026-08-12   NaN     8.25     2026-08-06       True   8.25
43 2026-08-13   NaN     8.25     2026-08-06       True   8.25
44 2026-08-14   NaN     8.25     2026-08-06       True   8.25
45 2026-08-15   NaN     8.25     2026-08-06       True   8.25
46 2026-08-16   NaN     8.25     2026-08-06       True   8.25
47 2026-08-17  8.75     8.75     2026-08-20      False   8.25
48 2026-08-18  8.75     8.75     2026-08-20      False   8.25
49 2026-08-19  8.75     8.75     2026-08-20      False   8.25
50 2026-08-20  8.75     8.75     2026-08-20      False   8.75
51 2026-08-21  8.75     8.75     2026-08-20      False   8.75
52 2026-08-22  8.75     8.75     2026-08-20      False   8.75
53 2026-08-23  8.75     8.75     2026-08-20      False   8.75
54 2026-08-24  9.00     9.00     2026-08-27      False   8.75
55 2026-08-25  9.00     9.00     2026-08-27      False   8.75
56 2026-08-26  9.00     9.00     2026-08-27      False   8.75
57 2026-08-27  9.00     9.00     2026-08-27      False   9.00
58 2026-08-28  9.00     9.00     2026-08-27      False   9.00
59 2026-08-29  9.00     9.00     2026-08-27      False   9.00
60 2026-08-30  9.00     9.00     2026-08-27      False   9.00
61 2026-08-31  9.00     9.00     2026-08-27      False   9.00
62 2026-09-01  9.00     9.00     2026-08-27      False   9.00

## 4. Проверки

**4.1. Независимый расчёт «в лоб».** Даты отчёта ищутся простым циклом по правилу ТЗ: для д —
каждая непустая строка, для м/н — непустая строка после пустой или с новым значением. Затем
на каждую дату t берётся отчёт с наибольшей `report_date + lag <= t`. Этот код не использует lagkit.

In [7]:
def expected_known(raw: pd.Series, lag: int, freq: str, calendar) -> pd.Series:
    reports, prev = [], None
    for d, v in raw.items():
        if pd.isna(v):
            prev = None
            continue
        if freq == "д" or prev is None or v != prev:
            reports.append((d + pd.Timedelta(days=lag), d, v))  # (available, report, value)
        prev = v
    out = {}
    for t in calendar:
        known = [r for r in reports if r[0] <= t]
        out[t] = max(known)[2] if known else np.nan
    return pd.Series(out)

known = lp.known().set_index("DATE")
raw = data.set_index("DATE")
for f, freq, lag in master.itertuples(index=False):
    exp = expected_known(raw[f], lag, freq, known.index)
    pd.testing.assert_series_equal(known[f], exp, check_names=False, check_freq=False)
    print(f"{f:11s} OK: known совпадает с независимым расчётом на всех {len(exp)} датах")

usd_rub     OK: known совпадает с независимым расчётом на всех 63 датах
cpi_mom     OK: known совпадает с независимым расчётом на всех 63 датах
deposits_w  OK: known совпадает с независимым расчётом на всех 63 датах

**4.2. Ключевые даты, посчитанные вручную.**

In [8]:
checks = [
    # factor,      дата,         ожидаемое значение, почему
    ("usd_rub",    "2026-07-01", np.nan, "первый курс (01.07) известен только с 02.07"),
    ("usd_rub",    "2026-07-02", 90.0,   "курс за 01.07"),
    ("usd_rub",    "2026-09-01", 96.1,   "курс за 31.08 (01.09 в витрине пуст — не важно)"),
    ("cpi_mom",    "2026-07-30", np.nan, "отчёт 01.07 + 30 = 31.07, ещё не известен"),
    ("cpi_mom",    "2026-07-31", 100.0,  "01.07 + 30"),
    ("cpi_mom",    "2026-08-30", 100.0,  "август (101.5) ещё не опубликован"),
    ("cpi_mom",    "2026-08-31", 101.5,  "01.08 + 30"),
    ("deposits_w", "2026-07-03", np.nan, "отчёт 01.07 + 3 = 04.07"),
    ("deposits_w", "2026-07-04", 7.0,    "01.07 + 3"),
    ("deposits_w", "2026-07-08", 7.0,    "отчёт 06.07 известен с 09.07"),
    ("deposits_w", "2026-07-09", 7.25,   "06.07 + 3"),
    ("deposits_w", "2026-08-06", 8.25,   "отчёт 03.08 + 3"),
    ("deposits_w", "2026-08-13", 8.25,   "сбой: отчёт 10.08 не пришёл, протягиваем 03.08"),
    ("deposits_w", "2026-08-19", 8.25,   "отчёт 17.08 известен только с 20.08"),
    ("deposits_w", "2026-08-20", 8.75,   "17.08 + 3"),
    ("deposits_w", "2026-09-01", 9.0,    "отчёт 24.08 + 3 = 27.08; 31.08–01.09 витрина протянула тот же отчёт"),
]
rows = []
for f, d, exp, why in checks:
    got = known.loc[d, f]
    ok = (np.isnan(exp) and np.isnan(got)) or np.isclose(got, exp)
    rows.append(dict(factor=f, DATE=d, expected=exp, known=got, ok=ok, why=why))
res = pd.DataFrame(rows)
display(res)
assert res["ok"].all()

        factor        DATE  expected   known    ok                                                why
0      usd_rub  2026-07-01       NaN     NaN  True        первый курс (01.07) известен только с 02.07
1      usd_rub  2026-07-02     90.00   90.00  True                                      курс за 01.07
2      usd_rub  2026-09-01     96.10   96.10  True    курс за 31.08 (01.09 в витрине пуст — не важно)
3      cpi_mom  2026-07-30       NaN     NaN  True          отчёт 01.07 + 30 = 31.07, ещё не известен
4      cpi_mom  2026-07-31    100.00  100.00  True                                         01.07 + 30
5      cpi_mom  2026-08-30    100.00  100.00  True                  август (101.5) ещё не опубликован
6      cpi_mom  2026-08-31    101.50  101.50  True                                         01.08 + 30
7   deposits_w  2026-07-03       NaN     NaN  True                            отчёт 01.07 + 3 = 04.07
8   deposits_w  2026-07-04      7.00    7.00  True                                          01.07 + 3
9   deposits_w  2026-07-08      7.00    7.00  True                       отчёт 06.07 известен с 09.07
10  deposits_w  2026-07-09      7.25    7.25  True                                          06.07 + 3
11  deposits_w  2026-08-06      8.25    8.25  True                                    отчёт 03.08 + 3
12  deposits_w  2026-08-13      8.25    8.25  True     сбой: отчёт 10.08 не пришёл, протягиваем 03.08
13  deposits_w  2026-08-19      8.25    8.25  True                отчёт 17.08 известен только с 20.08
14  deposits_w  2026-08-20      8.75    8.75  True                                          17.08 + 3
15  deposits_w  2026-09-01      9.00    9.00  True  отчёт 24.08 + 3 = 27.08; 31.08–01.09 витрина п...

**4.3. Журнал: середина блока наследует дату доступности блока, хвост и сбой помечены `is_filled`.**

In [9]:
j = lp.journal(layout="long").set_index(["factor", "DATE"])
assert j.loc[("cpi_mom", "2026-07-15"), "available_date"] == pd.Timestamp("2026-07-31")
assert j.loc[("cpi_mom", "2026-09-01"), "available_date"] == pd.Timestamp("2026-08-31")
assert j.loc[("deposits_w", "2026-07-08"), "available_date"] == pd.Timestamp("2026-07-09")
gap = j.loc["deposits_w"].loc["2026-08-10":"2026-08-16"]
assert gap["is_filled"].all() and (gap["value"] == 8.25).all()
assert j.loc[("usd_rub", "2026-09-01"), "is_filled"]
assert j.loc[("usd_rub", "2026-08-31"), "available_date"] == pd.Timestamp("2026-09-01")
print("журнал OK")

журнал OK

**4.4. Инвариант отсутствия утечки и диагностика пропуска.**

In [10]:
kl = lp.known(layout="long")
assert (kl["available_date"] <= kl["DATE"]).all()
print(f"available_date <= DATE во всех {len(kl)} строках known")

d = lp.diagnostics()
gap_diag = d[(d["check"] == "missing_reports") & (d["factor"] == "deposits_w")]
assert len(gap_diag) == 1
print(gap_diag["message"].iloc[0])
assert (d["severity"] != "error").all()

available_date <= DATE во всех 155 строках known
Пропуски отчётов: 1 разрыв(ов), всего пропущено периодов 1 (03.08.2026 → 17.08.2026: пропущено 1); значения протянуты

## 5. Сохранение

In [11]:
paths = lp.save(view="all", layout="wide")
for name, p in paths.items():
    print(f"{name:14s} {p}")
pd.read_csv(paths["known_wide"]).tail(5)

raw_wide       synthetic/lag_output/raw_wide.csv
journal_wide   synthetic/lag_output/journal_wide.csv
known_wide     synthetic/lag_output/known_wide.csv
lags           synthetic/lag_output/lags.csv
diagnostics    synthetic/lag_output/diagnostics.csv

          DATE  usd_rub  cpi_mom  deposits_w
58  2026-08-28     95.7    100.0         9.0
59  2026-08-29     95.8    100.0         9.0
60  2026-08-30     95.9    100.0         9.0
61  2026-08-31     96.0    101.5         9.0
62  2026-09-01     96.1    101.5         9.0